version: '3'

services:
  bot:
    image: ghcr.io/krishukr/telegram-cjk-search-bot:dev
    restart: unless-stopped
    volumes:
      - ./history:/app/history
    environment:
      - TELOXIDE_TOKEN=xxx:xxx
      - MEILISEARCH_HOST=http://meilisearch:7700
      - TZ=Asia/Shanghai
      - RUST_LOG=INFO,telegram_cjk_search_bot=INFO
    depends_on:
      - meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.2
    restart: unless-stopped
    volumes:
      - ./meili_data:/meili_data
