name: Test & Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: "x86_64"
          - arch: "aarch64"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@v9
      - name: Build image
        run: nix build .#dockerImage-${{ matrix.arch }}
      - name: Upload image to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oci-image-${{ matrix.arch }}-linux
          path: result
          if-no-files-found: error
          compression-level: 0
