name: Test & Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: "x86_64"
          - arch: "aarch64"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup cache
        uses: cachix/cachix-action@v15
        with:
          name: krishukr
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build image
        run: nix build .#dockerImage-${{ matrix.arch }}
      - name: Upload image to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oci-image-${{ matrix.arch }}-linux
          path: result
          if-no-files-found: error
          compression-level: 0
