name: Test

on: [ pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - system: "x86_64-linux"
          # - system: "aarch64-linux"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Setup cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Build image
        run: nix build .#packages.${{ matrix.system }}.default
      - name: Upload image to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oci-image-${{ matrix.system }}
          path: result
          if-no-files-found: error
          compression-level: 0
