name: Test

on: [ pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup cache
        uses: cachix/cachix-action@v16
        with:
          name: krishukr
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build dynamic binary
        run: nix build .#bin
      - name: Upload binary to artifacts
        uses: actions/upload-artifact@v4
        with:
            path: ./result/bin/
